Sekretariat
KSIUJ/ksicamp-the-game pull request #26
Opened 2018-11-17 17:26 UTC by skypio

2018-11-17 17:28 UTC, phoe commented on rooms/sekretariat.cpp
> +      wait_s(10);
ej no, dziesięć sekund to o wiele za długo

2018-11-17 17:29 UTC, phoe requested changes

2018-11-17 17:29 UTC, phoe commented on rooms/sekretariat.cpp
> +      wait_s(3);
tak samo tu

2018-11-17 17:29 UTC, phoe commented on util.cpp
> +  std::string roomStrings[] = {"KSI",
poprzednie było lepsze

2018-11-17 18:07 UTC, skypio commented on rooms/sekretariat.cpp
> +      wait_s(10);
ale jak się czyta całość to nie daje te 10s akurat czasu na przeczytanie i przechodzi potem dalej?

2018-11-17 18:09 UTC, phoe commented on rooms/sekretariat.cpp
> +      wait_s(10);
niektórzy czytają szybciej - nie ma tutaj one-size-fits-all.
polecam metodę z manualną progresją przez wciśnięcie Entera:
```cpp
std::cout << "[Wciśnij Enter, żeby przejść dalej...]";
std::string tmp;
std::cin >> tmp;
```

2018-11-17 18:11 UTC, skypio commented on rooms/sekretariat.cpp
> +      wait_s(10);
wiem wiem,  jestem tego świadomy 
hmm pomyślę o tym enterze, jak będę miał chwilkę to zamienię to

2018-12-05 10:28 UTC, SzymonSmykala commented
@skypio any progress?

2018-12-15 09:45 UTC, phoe approved these changes

2018-12-15 09:50 UTC, merged