Master without binary
KSIUJ/ksicamp-the-game pull request #31
Opened 2018-12-01 11:52 UTC by seqre

Do not PR, change master to this one

2018-12-01 12:06 UTC, apardyl commented
wtf?

2018-12-01 12:07 UTC, phoe commented
![zrzut ekranu z 2018-12-01 13-06-16](https://user-images.githubusercontent.com/15045546/49328047-e78dc800-f569-11e8-90bf-62985c3b4590.png)

There are still conflicts in the files. The resulting branch should not be any different than `master` other than missing the `main` file.

Are you sure that you are working on a fresh master branch?

2018-12-01 12:08 UTC, phoe commented
@apardyl Próbujemy przepisać historię, żeby wywalić przypadkowo zacommitowaną binarkę `main` z głównego katalogu projektu.

2018-12-03 21:05 UTC, seqre commented
Branch repaired, ready to change it to master

2018-12-05 07:33 UTC, phoe commented
![zrzut ekranu z 2018-12-05 08-32-19](https://user-images.githubusercontent.com/15045546/49497275-4acc7280-f868-11e8-8f72-dfc4d787a42d.png)

xD

No nie no, dokładnie tego miałeś nie robić - w tym momencie twój branch zawiera z powrotem binarkę, bo zmerge'owałeś się z masterem.

https://github.com/KSIUJ/ksicamp-the-game/blob/master_without_binary/main

2018-12-05 15:05 UTC, phoe requested changes
DO NOT MERGE with master.

2018-12-06 13:35 UTC, seqre commented
Now?

2018-12-15 09:27 UTC, merged